### ISSUE TITLE
Fix bugs or features

### ISSUE THREAD

**Issue by RevenBot** [Clueless-Aware/BackendAPI#37]
```[tasklist]
### Tasks
- [ ] Fix the "id" field must be generated from django.
- [ ] Fix the pagination, set pagination number [SEE](https://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination)
- [ ] Fix the artist serializer  [SEE](https://www.django-rest-framework.org/api-guide/relations/)
```
