### ISSUE TITLE
Update models

### ISSUE THREAD

**Issue by Aiuola** [Clueless-Aware/BackendAPI#39]
```[tasklist]
### Tasks
- [x] Update user model with more fields
- [x] Favorite model
- [ ] User request model
- [ ] Tracking of user requests?
- [ ] Tracking of searches?
```
