### ISSUE TITLE
User requests Model

### ISSUE THREAD

**Issue by Aiuola** [Clueless-Aware/BackendAPI#45]
```[tasklist]
### Tasks
- [x] Create a new model in accounts/user for making requests
- [ ] Update Favorites model to better suit the frontend
- [x] Here is an example of the Request model:
- [x] Email backend in save method
```

- Source - Email
- Destination - Email
- Subject - String (50 chars)
- Content - String
- Date - DateField
